name: Build and deploy Node.js app to Azure Web App - chatgpt-custom

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: '18.x'

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Zip artifact for deployment
        run: zip release.zip ./* -r

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v3
        with:
          name: node-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v3
        with:
          name: node-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      - name: Modify /etc/hosts for fake DNS
        run: |
          sudo -- sh -c -e "echo '20.90.134.32    ASP-researchrg-9119.appserviceenvironment.net' >> /etc/hosts";
          sudo -- sh -c -e "echo '20.90.134.32    scm.ASP-researchrg-9119.appserviceenvironment.net' >> /etc/hosts";
          sudo -- sh -c -e "echo '20.90.134.32    dgchatgpt.scm.ASP-researchrg-9119.appserviceenvironment.net' >> /etc/hosts";

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'chatgpt-custom'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_4C6FBC2400A64CAC90C9CD209A8EE3C8 }}
          package: .
